/**
 * 从 Factory Idle 浏览器 bundle 恢复。
 * AMD 模块：config/event/GameUiEvent
 */
define("config/event/GameUiEvent", [], function() {
  return { SHOW_FACTORY: "SHOW_FACTORY", SHOW_FACTORIES: "SHOW_FACTORIES", SHOW_RESEARCH: "SHOW_RESEARCH", SHOW_UPGRADES: "SHOW_UPGRADES", SHOW_ACHIEVEMENTS: "SHOW_ACHIEVEMENTS", SHOW_HELP: "SHOW_HELP", SHOW_STATISTICS: "SHOW_STATISTICS", SHOW_PURCHASES: "SHOW_PURCHASES", SHOW_SETTINGS: "SHOW_SETTINGS", SHOW_TIME_TRAVEL: "SHOW_TIME_TRAVEL" };
});
